Controllers/PartsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryTracker.Data;
using InventoryTracker.Models.DomainComponents;

namespace InventoryTracker.Controllers
{
    public class PartsController : Controller // На діаграмі класів діаграма - (5)
    {
        private readonly InventoryDbContext _db;

        public PartsController(InventoryDbContext db)
        {
            _db = db;
        }

        public IActionResult PartsIndex()
        {
            var cases = _db.Cases.ToList();
            var drives = _db.Drives.ToList();
            var graphicsCards = _db.GraphicsCards.ToList();
            var motherboards = _db.Motherboards.ToList();
            var powerSupplies = _db.PowerSupplies.ToList();
            var processors = _db.Processors.ToList();
            var rams = _db.RAMs.ToList();

            PartsList partsList = new PartsList
            {
                Cases = cases,
                Drives = drives,
                GraphicsCards = graphicsCards,
                Motherboards = motherboards,
                PowerSupplies = powerSupplies,
                Processors = processors,
                RAMs = rams
            };
            return View(partsList);
        }

        //Процесори-----------------------------------------------------------------------------------------------------------------
        //Створення процесора
        public IActionResult CreateProcessor()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateProcessor(Processor obj)
        {
            if (ModelState.IsValid)
            {
                _db.Processors.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно додано";
                return RedirectToAction("PartsIndex");
            }
            return View(obj);
        }

        //Редагування процесора
        public IActionResult UpdateProcessor(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var processorFromDb = _db.Processors.Find(id);
            if (processorFromDb == null)
            {
                return NotFound();
            }
            return View(processorFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateProcessor(Processor obj)
        {
            if (ModelState.IsValid)
            {
                _db.Processors.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно оновлено";
                return RedirectToAction("PartsIndex");
            }
            return View(obj);
        }

        //Видалення процесора
        public IActionResult DeleteProcessor(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var processorFromDb = _db.Processors.Find(id);
            if (processorFromDb == null)
            {
                return NotFound();
            }
            return View(processorFromDb);
        }

        [HttpPost("DeleteProcessorPOST")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProcessorPost(int? id)
        {
            var obj = _db.Processors.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Processors.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Товар успішно видалено";
            return RedirectToAction("PartsIndex");
        }


        //Материнські плати----------------------------------------------------------------------------------------------------------
        //Створення материнської плати
        public IActionResult CreateMotherboard()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateMotherboard(Motherboard obj)
        {
            if (ModelState.IsValid)
            {
                _db.Motherboards.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно додано";
                return RedirectToAction("PartsIndex");
            }
            return View(obj);
        }

        //Редагування материнської плати
        public IActionResult UpdateMotherboard(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var motherboardFromDb = _db.Motherboards.Find(id);
            if (motherboardFromDb == null)
            {
                return NotFound();
            }
            return View(motherboardFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateMotherboard(Motherboard obj)
        {
            if (ModelState.IsValid)
            {
                _db.Motherboards.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно оновлено";
                return RedirectToAction("PartsIndex");
            }
            return View(obj);
        }

        //Видалення материнської плати
        public IActionResult DeleteMotherboard(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var motherboardFromDb = _db.Motherboards.Find(id);
            if (motherboardFromDb == null)
            {
                return NotFound();
            }
            return View(motherboardFromDb);
        }

        [HttpPost("DeleteMotherboardPost")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteMotherboardPost(int? id)
        {
            var obj = _db.Motherboards.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Motherboards.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Товар успішно видалено";
            return RedirectToAction("PartsIndex");
        }


        //Відеокарти----------------------------------------------------------------------------------------------------------
        //Створення відеокарти
        public IActionResult CreateGPU()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateGPU(GraphicsCard obj)
        {
            if (ModelState.IsValid)
            {
                _db.GraphicsCards.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно додано";
                return RedirectToAction("PartsIndex");
            }
            return View(obj);
        }

        //Редагування відеокарти
        public IActionResult UpdateGPU(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var graphicsCardFromDb = _db.GraphicsCards.Find(id);
            if (graphicsCardFromDb == null)
            {
                return NotFound();
            }
            return View(graphicsCardFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateGPU(GraphicsCard obj)
        {
            if (ModelState.IsValid)
            {
                _db.GraphicsCards.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно оновлено";
                return RedirectToAction("PartsIndex");
            }
            return View(obj);
        }

        //Видалення відеокарти
        public IActionResult DeleteGPU(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var graphicsCardFromDb = _db.GraphicsCards.Find(id);
            if (graphicsCardFromDb == null)
            {
                return NotFound();
            }
            return View(graphicsCardFromDb);
        }

        [HttpPost("DeleteGPUPost")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteGPUPost(int? id)
        {
            var obj = _db.GraphicsCards.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.GraphicsCards.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Товар успішно видалено";
            return RedirectToAction("PartsIndex");
        }

        //Пристрої накопичення----------------------------------------------------------------------------------------------------------
        //Створення пристрою накопичення
        public IActionResult CreateDrive()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateDrive(Drive obj)
        {
            if (ModelState.IsValid)
            {
                _db.Drives.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно додано";
                return RedirectToAction("PartsIndex");
            }
            return View(obj);
        }

        //Редагування відеокарти
        public IActionResult UpdateDrive(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var drivesFromDb = _db.Drives.Find(id);
            if (drivesFromDb == null)
            {
                return NotFound();
            }
            return View(drivesFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateDrive(Drive obj)
        {
            if (ModelState.IsValid)
            {
                _db.Drives.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно оновлено";
                return RedirectToAction("PartsIndex");
            }

Views/Shared/_Layout.cshtml
<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryTracker</title>
    @* Додаємо всі необхідні посилання для відображення у проекті :
    bootstrap, bootswatchTheme - теми та стилі
    toastr - для сповіщень *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> 
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" /> 
    <link rel="stylesheet" href="~/InventoryTracker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 text-bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InventoryTracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Каталог
                            </a>
                            <ul class="dropdown-menu"> 
                                <li><a class="dropdown-item" asp-area="" asp-controller="Parts"       asp-action="PartsIndex">Комплектуючі до ПК</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Peripherals" asp-action="PeripheralsIndex">Периферія для ПК</a></li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Support">Підтримка</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Інформація</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @* Використовуємо створений partial "_Notification" view для відображення сповіщень *@
            <partial name="_Notification"></partial> 
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark" style="position:fixed">
        <div class="container">
            &copy; 2023 - InventoryTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Інформація</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
    

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}