Controllers/PeripheralsController.cs
using Microsoft.AspNetCore.Mvc;
using InventoryTracker.Data;
using InventoryTracker.Models.DomainComponents;
using InventoryTracker.Models.DomainPeripherals;


namespace InventoryTracker.Controllers
{
    public class PeripheralsController : Controller // На діаграмі класів діаграма - (1)
    {
        private readonly InventoryDbContext _db;

        public PeripheralsController(InventoryDbContext db)
        {
            _db = db;
        }

        public IActionResult PeripheralsIndex()
        {
            var keyboards = _db.Keyboards.ToList();
            var mice = _db.Mice.ToList();
            var mousepads = _db.Mousepads.ToList();

            PeripheralsList peripheralsList = new PeripheralsList
            {
                Keyboards = keyboards,
                Mice = mice,
                Mousepads = mousepads,
            };
            return View(peripheralsList);


        }

        //Клавіатури-----------------------------------------------------------------------------------------------------------------
        //Створення клавіатури
        public IActionResult CreateKeyboard()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateKeyboard(Keyboard obj)
        {
            if (ModelState.IsValid)
            {
                _db.Keyboards.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно додано";
                return RedirectToAction("PeripheralsIndex");
            }
            return View(obj);
        }

        //Редагування клавіатури
        public IActionResult UpdateKeyboard(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var keyboardFromDb = _db.Keyboards.Find(id);
            if (keyboardFromDb == null)
            {
                return NotFound();
            }
            return View(keyboardFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateKeyboard(Keyboard obj)
        {
            if (ModelState.IsValid)
            {
                _db.Keyboards.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно оновлено";
                return RedirectToAction("PeripheralsIndex");
            }
            return View(obj);
        }

        //Видалення клавіатури
        public IActionResult DeleteKeyboard(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var keyboardFromDb = _db.Keyboards.Find(id);
            if (keyboardFromDb == null)
            {
                return NotFound();
            }
            return View(keyboardFromDb);
        }

        [HttpPost("DeleteKeyboardPOST")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteKeyboardPOST(int? id)
        {
            var obj = _db.Keyboards.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Keyboards.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Товар успішно видалено";
            return RedirectToAction("PeripheralsIndex");
        }

        //Миші-----------------------------------------------------------------------------------------------------------------
        //Створення мишок
        public IActionResult CreateMice()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateMice(Mouse obj)
        {
            if (ModelState.IsValid)
            {
                _db.Mice.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно додано";
                return RedirectToAction("PeripheralsIndex");
            }
            return View(obj);
        }

        //Редагування мишок
        public IActionResult UpdateMouse(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var mouseFromDb = _db.Mice.Find(id);
            if (mouseFromDb == null)
            {
                return NotFound();
            }
            return View(mouseFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateMouse(Mouse obj)
        {
            if (ModelState.IsValid)
            {
                _db.Mice.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно оновлено";
                return RedirectToAction("PeripheralsIndex");
            }
            return View(obj);
        }

        //Видалення мишок
        public IActionResult DeleteMouse(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var mouseFromDb = _db.Mice.Find(id);
            if (mouseFromDb == null)
            {
                return NotFound();
            }
            return View(mouseFromDb);
        }

        [HttpPost("DeleteMousePOST")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteMousePOST(int? id)
        {
            var obj = _db.Mice.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Mice.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Товар успішно видалено";
            return RedirectToAction("PeripheralsIndex");
        }

        //Килимки-----------------------------------------------------------------------------------------------------------------
        //Створення килимків
        public IActionResult CreateMousepad()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateMousepad(Mousepad obj)
        {
            if (ModelState.IsValid)
            {
                _db.Mousepads.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно додано";
                return RedirectToAction("PeripheralsIndex");
            }
            return View(obj);
        }

        //Редагування килимків
        public IActionResult UpdateMousepad(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var mpadFromDb = _db.Mousepads.Find(id);
            if (mpadFromDb == null)
            {
                return NotFound();
            }
            return View(mpadFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateMousepad(Mousepad obj)
        {
            if (ModelState.IsValid)
            {
                _db.Mousepads.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Товар успішно оновлено";
                return RedirectToAction("PeripheralsIndex");
            }
            return View(obj);
        }

        //Видалення килимків
        public IActionResult DeleteMousepad(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var mpadFromDb = _db.Mousepads.Find(id);
            if (mpadFromDb == null)
            {
                return NotFound();
            }
            return View(mpadFromDb);
        }

        [HttpPost("DeleteMousepadPOST")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteMousepadPOST(int? id)
        {
            var obj = _db.Mousepads.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Mousepads.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Товар успішно видалено";
            return RedirectToAction("PeripheralsIndex");
        }


    }
}

Views/Peripherals/CreateKeyboard.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Keyboard

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Додавання</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="FormFactor" />
			<label asp-for="FormFactor"></label>
			<span asp-validation-for="FormFactor" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="KeycapType"></label>
			<input asp-for="KeycapType" />
			<span asp-validation-for="KeycapType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="KeycapMaterial"></label>
			<input asp-for="KeycapMaterial" />
			<span asp-validation-for="KeycapMaterial" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Color"></label>
			<input asp-for="Color" />
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Type"></label>
			<input asp-for="Type" />
			<span asp-validation-for="Type" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Layout"></label>
			<input asp-for="Layout" />
			<span asp-validation-for="Layout" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ConnectionType"></label>
			<input asp-for="ConnectionType" />
			<span asp-validation-for="ConnectionType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Додати</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>

Views/Peripherals/CreateMice.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Mouse

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Додавання</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Color" />
			<label asp-for="Color"></label>
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="DPIRange"></label>
			<input asp-for="DPIRange" />
			<span asp-validation-for="DPIRange" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ConnectionType"></label>
			<input asp-for="ConnectionType" />
			<span asp-validation-for="ConnectionType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Додати</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>

Views/Peripherals/CreateMousepad.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Mousepad

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Додавання</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Size" />
			<label asp-for="Size"></label>
			<span asp-validation-for="Size" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Dimensions"></label>
			<input asp-for="Dimensions" />
			<span asp-validation-for="Dimensions" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Color"></label>
			<input asp-for="Color" />
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Material"></label>
			<input asp-for="Material" />
			<span asp-validation-for="Material" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Додати</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>

Views/Peripherals/DeleteKeyboard.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Keyboard	

<form method="post" asp-controller="Peripherals" asp-action="DeleteKeyboardPOST" asp-route-id="@Model.KeyboardId">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Видалити</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<input type="hidden" asp-for="KeyboardId" />
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" disabled />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" disabled />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="FormFactor" disabled />
			<label asp-for="FormFactor"></label>
			<span asp-validation-for="FormFactor" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="KeycapType" disabled />
			<label asp-for="KeycapType"></label>
			<span asp-validation-for="KeycapType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="KeycapMaterial" disabled />
			<label asp-for="KeycapMaterial"></label>
			<span asp-validation-for="KeycapMaterial" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Color" disabled />
			<label asp-for="Color"></label>
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Type" disabled />
			<label asp-for="Type"></label>
			<span asp-validation-for="Type" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Layout"></label>
			<input asp-for="Layout" disabled />
			<span asp-validation-for="Layout" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ConnectionType"></label>
			<input asp-for="ConnectionType" disabled />
			<span asp-validation-for="ConnectionType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" disabled />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" disabled />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Видалити</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>

Views/Peripherals/DeleteMouse.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Mouse

<form method="post" asp-controller="Peripherals" asp-action="DeleteMousePOST" asp-route-id="@Model.MouseId">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Видалити</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<input type="hidden" asp-for="MouseId" />
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" disabled />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" disabled />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Color" disabled />
			<label asp-for="Color"></label>
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="DPIRange" disabled />
			<label asp-for="DPIRange"></label>
			<span asp-validation-for="DPIRange" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="ConnectionType" disabled />
			<label asp-for="ConnectionType"></label>
			<span asp-validation-for="ConnectionType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" disabled />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" disabled />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Видалити</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>

Views/Peripherals/DeleteMousepad.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Mousepad

<form method="post" asp-controller="Peripherals" asp-action="DeleteMousepadPOST" asp-route-id="@Model.MousepadId">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Видалити</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<input type="hidden" asp-for="MousepadId" />
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" disabled />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" disabled />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Size" disabled />
			<label asp-for="Size"></label>
			<span asp-validation-for="Size" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Dimensions" disabled />
			<label asp-for="Dimensions"></label>
			<span asp-validation-for="Dimensions" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Color" disabled />
			<label asp-for="Color"></label>
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Material" disabled />
			<label asp-for="Material"></label>
			<span asp-validation-for="Material" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" disabled />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" disabled />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Видалити</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>

Views/Peripherals/UpdateKeyboard.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Keyboard	

<form method="post" asp-action="UpdateKeyboard">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Редагувати</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<input type="hidden" asp-for="KeyboardId" />
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="FormFactor" />
			<label asp-for="FormFactor"></label>
			<span asp-validation-for="FormFactor" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="KeycapType"></label>
			<input asp-for="KeycapType" />
			<span asp-validation-for="KeycapType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="KeycapMaterial"></label>
			<input asp-for="KeycapMaterial" />
			<span asp-validation-for="KeycapMaterial" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Color"></label>
			<input asp-for="Color" />
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Type"></label>
			<input asp-for="Type" />
			<span asp-validation-for="Type" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Layout"></label>
			<input asp-for="Layout" />
			<span asp-validation-for="Layout" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ConnectionType"></label>
			<input asp-for="ConnectionType" />
			<span asp-validation-for="ConnectionType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Оновити</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>

Views/Peripherals/UpdateMouse.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Mouse

<form method="post" asp-action="UpdateMouse">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Редагувати</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<input type="hidden" asp-for="MouseId" />
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Color" />
			<label asp-for="Color"></label>
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="DPIRange"></label>
			<input asp-for="DPIRange" />
			<span asp-validation-for="DPIRange" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ConnectionType"></label>
			<input asp-for="ConnectionType" />
			<span asp-validation-for="ConnectionType" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Оновити</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>

Views/Peripherals/UpdateMousepad.cshtml
@using InventoryTracker.Models.DomainPeripherals
@model Mousepad

<form method="post" asp-action="UpdateMousepad">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Редагувати</h2>
		</div>
		<div asp-validation-summary="All"></div>
		<input type="hidden" asp-for="MousepadId" />
		<div class="mb-3">
			<label asp-for="Manufacturer"></label>
			<input asp-for="Manufacturer" />
			<span asp-validation-for="Manufacturer" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Model"></label>
			<input asp-for="Model" />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Size" />
			<label asp-for="Size"></label>
			<span asp-validation-for="Size" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Dimensions"></label>
			<input asp-for="Dimensions" />
			<span asp-validation-for="Dimensions" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Color"></label>
			<input asp-for="Color" />
			<span asp-validation-for="Color" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Material"></label>
			<input asp-for="Material" />
			<span asp-validation-for="Material" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<input asp-for="Price" />
			<label asp-for="Price"></label>
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="AmountInStock"></label>
			<input asp-for="AmountInStock" />
			<span asp-validation-for="AmountInStock" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Оновити</button>
		<a asp-controller="Peripherals" asp-action="PeripheralsIndex" class="btn btn-secondary" style="width:150px">
			Назад до каталогу
		</a>
	</div>

</form>